"""Record the reviewed current Moss Tonic revision without claiming acceptance."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[2];folder=root/'Docs/BlenderRebuild/MossTonic'
mesh=json.loads((folder/'mesh-validation.json').read_text())
result={'revision':'pane_grid_rim_leaf_and_refraction','parts':mesh['parts'],'triangles':mesh['triangles'],'changes':['Continuous glass shell subdivided into a 12-row pane grid with per-face teal tint variation','Narrower stepped mint lip, fuller corner collars and separate turquoise corner facets','Warmer golden cork/cord palette and more rounded cork edges','Leaf and paired cord loops moved around the neck; enlarged leaf hangs below the loops','Unreal refraction displacement scaled by 0.045 to avoid reading distant scene color through the small bottle'],'studio_front':'front.png','studio_rear':'rear.png','world_views':['PaneRefinement/unreal-viewport.png','PaneRefinement/Front/unreal-viewport.png','PaneRefinement/Side/unreal-viewport.png'],'visually_checked':True,'remaining':['Exact pane coloration and irregular source block placement','Rim block silhouette and neck opacity','Leaf contour and binding-loop proportions','World lighting is much cooler and darker under the awning'],'accepted_fidelity':False,'physical_optics_limit':'Blender transmission retains IOR 1.46/1.33. Unreal refraction input is 1 + (IOR - 1) * 0.045, an explicit screen-space approximation; this is not optical equivalence.'}
(folder/'visual-review.json').write_text(json.dumps(result,indent=2))
r=json.loads((folder/'source-adaptation.json').read_text());r['status']='imported_with_visual_refinement_open';r['revision']=result['revision'];(folder/'source-adaptation.json').write_text(json.dumps(r,indent=2))
readme=root/'Docs/BlenderRebuild/README.md';text=readme.read_text(encoding='utf-8')
start=text.index('`moss_tonic.png` ');end=text.index('The south bridge joint now has',start)
text=text[:start]+'''`moss_tonic.png` has a normal editable Blender project at `SourceAssets/Blender/MossTonic/MossTonic.blend`. Its current revision contains 351 closed parts and 47,396 exported triangles: a hollow glass shell with a 12-row pane grid, separate liquid, stepped shoulders, a narrower irregular mint rim, rounded tiled cork, raised blank label, gold cord loops and an enlarged veined leaf hanging from the side. The corner collars and turquoise facets now more closely follow the source. Three material slots and three packed texture maps are preserved. Earlier drafts are archived under `MossTonic/FirstPhysical/` and the source's `Revisions/FirstPhysical/` folder.

`Blender_MossTonic_MarketCounter` remains at (241.4, 623, 634.594) cm in HomesteadBlender, with uniform scale 0.22 and a height of 18.392 cm. The saved world was reloaded after reimport; its transform, all three shader bindings and scalar parameters, source FBX hash, texture color spaces and nine counter-support samples passed. Its lowest feet are 0.02 cm above the highest sampled countertop surface. The market stall and surrounding props remain intact. Sampled Blender volume membership separately checks the solid bottom, side wall, liquid-filled cavity, empty neck and open mouth.

Current studio images are `MossTonic/front.png` and `rear.png`; the native world views are under `MossTonic/PaneRefinement/`, including separate front and side views. The earlier bright refracted strip is absent from these three inspected views after scaling Unreal's screen-space displacement by 0.045. Blender retains glass/liquid IOR values of 1.46/1.33; Unreal uses `1 + (IOR - 1) * 0.045` for the refraction input, an explicit approximation for this small bottle. This does not certify physical optical equivalence or all-view transparency sorting.

The pane pattern, rim silhouette, neck opacity, leaf contour and loop proportions still differ from the concept. The stall's lighting remains cooler and darker than the source studio. Rear surfaces are inferred. The model has not been accepted as a perfect match, and gameplay pickup, liquid simulation and performance remain untested. `MossTonic/WorldFront/` is the previous physical revision and `MossTonic/World/` is its earlier obstructed placement.

'''+text[end:]
text=text.replace('All three authoring files now contain only their own asset scene, with packed textures.','These authoring files contain their own asset scene with packed dependencies; Cottage uses one atlas, while Lantern and Sign use three maps each.')
readme.write_text(text,encoding='utf-8')
