"""Human-review page; image existence never grants fidelity acceptance."""
import json,struct,hashlib
from pathlib import Path
root=Path(__file__).resolve().parents[2];out=root/'Docs/BlenderRebuild'
cards=[];primary_count=0;variant_count=0
for folder in sorted(out.iterdir()):
    if not (folder/'mesh-validation.json').exists():continue
    key=folder.name
    mesh=json.loads((folder/'mesh-validation.json').read_text())
    if mesh.get('variant_of'):variant_count+=1
    else:primary_count+=1
    source=Path(mesh.get('source',key.lower()+'.png')).name
    data=(root/'SourceAssets/Blender'/key/('SM_Blender_'+key+'.glb')).read_bytes()
    magic,version,total=struct.unpack_from('<III',data);size,kind=struct.unpack_from('<II',data,12);g=json.loads(data[20:20+size])
    assert magic==0x46546c67 and version==2 and total==len(data) and len(g['meshes'])==1 and len(g['scenes'])==1
    assert all('TEXCOORD_0' in p['attributes'] and 'NORMAL' in p['attributes'] for p in g['meshes'][0]['primitives'])
    (folder/'glb-validation.json').write_text(json.dumps({'meshes':1,'scenes':1,'uv_and_normals':True,'bytes':len(data),'visual_acceptance':False},indent=2))
    variant_note=('Placement variant of '+mesh['variant_of']+': '+mesh.get('variant_purpose','')) if mesh.get('variant_of') else ''
    cards.append(f'<article><h2>{key}</h2><p>{variant_note}</p><div class="views"><figure><img src="../../SourceAssets/Voxel/{source}"><figcaption>Original concept</figcaption></figure><figure><img src="{key}/front.png"><figcaption>Blender front</figcaption></figure><figure><img src="{key}/rear.png"><figcaption>Blender rear — inferred unseen surfaces</figcaption></figure></div><p><a href="../../SourceAssets/Blender/{key}/{key}.blend">Editable Blender source</a> · {mesh["triangles"]:,} triangles · visual refinement remains open</p></article>')
page='''<!doctype html><meta charset="utf-8"><title>Terrarium · Blender reference review</title>
<style>body{margin:36px;background:#22251e;color:#e6e1d5;font:16px/1.5 system-ui}h1{font-size:32px}a{color:#c7d599}.views{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}figure{margin:0}img{width:100%;height:500px;object-fit:contain;background:#33382e}figcaption{color:#bbb7a8;padding:8px 0}article{border-top:1px solid #555f43;margin-top:28px;padding-top:12px}.world{height:auto}</style>
<h1>Terrarium · Blender reference review</h1><p>77 PNGs tracked · MODEL_COUNT Blender-authored models · 0 perfect-fidelity claims.</p>
<p>The original concepts are the visual target. Geometry validation, texture packing and successful Unreal imports are separate from visual fidelity. The full collection remains in progress.</p>'''+''.join(cards)+'''<h2>Native Unreal world capture</h2><img class="world" src="Props/unreal-viewport.png"><p>Working map: /Game/Terrarium/Blender/Maps/HomesteadBlender</p>'''
page=page.replace('MODEL_COUNT',str(primary_count))
page+=f'<p>{variant_count} separately tracked placement variants; these do not count as additional source concepts.</p>'
page+='<h2>Market stall in the homestead</h2><img class="world" src="MarketStall/unreal-viewport.png"><p>Upper walking path, beside the existing blue shed. Fidelity review remains open.</p>'
page+='<h2>Lodge on the upper terrace</h2><img class="world" src="Lodge/unreal-viewport.png"><p>Blender lodge added on a level part of the upper terrace. Fidelity review remains open.</p>'
page+='<h2>Civic hall beside the northern path</h2><img class="world" src="CivicHall/unreal-viewport.png"><p>Open belfry, hollow bell, stepped clock rim and arched portal. Fidelity review remains open.</p>'
page+='<h2>Blender shrubs in the existing planting</h2><img class="world" src="Environment/Shrubs/unreal-viewport.png"><p>618 shrub instances migrated. Existing ground plants overlap some flowers; visual refinement remains open.</p>'
page+='<h2>Blender rock on the bank</h2><img class="world" src="Environment/Rocks/unreal-viewport.png"><p>Seven bank rocks replaced with uniform scale to preserve authored proportions. Fidelity review remains open.</p>'
page+='<h2>Homestead tree in the world</h2><img class="world" src="HomesteadTree/unreal-viewport.png"><p>14 foliage instances replaced. Roots seated into the meadow. Crown layout and bark coloration still require refinement.</p>'
page+='<h2>Ancient tree in the north meadow</h2><img class="world" src="AncientTree/unreal-viewport.png"><p>Distinct tree.png model with five branch canopies, hanging vines, teal leaves and orange blossoms. Fidelity review remains open.</p>'
page+='<h2>Blender bridge across the river</h2><img class="world" src="RiverBridge/unreal-viewport.png"><p>Bridge placement variant from RiverCrossing. The full four-step reference assembly remains in its own Blender source.</p>'
page+='<h2>Blender stone steps between terraces</h2><img class="world" src="StoneStairs/unreal-viewport.png"><p>Earlier view of the eight-step placement variant. Four overlapping terrain instances were lowered beneath the flight. Meadow, rebuilt cliff groups and the subsequent TrailPatch replacement have BlockAll; decorative moss retains NoCollision. Character traversal remains untested. Stone coloration and pattern distribution require further reference matching.</p>'
page+='<h2>Blender wheat on the upper terrace</h2><img class="world" src="WheatPatch/unreal-viewport.png"><p>40 patches replaced with the shared square-stalk design, totaling 2,240 stalks. All roots checked against actual meadow tile footprints. The full 640-stalk concept bed is preserved separately in WheatField.blend. Shaft color bands, grain shapes and field-edge greenery still need refinement.</p>'
page+='<h2>Blender riverbank at the waterline</h2><img class="world" src="Riverbank/Actor/unreal-viewport.png"><p>Seven bank actors replaced with uniform footprint-area fitting. Their low green apron is exposed above the local water geometry. Left clump shape, cattail spacing and surface coloration still require reference matching.</p><h2>Riverbank foliage on the existing ledges</h2><img class="world" src="Riverbank/Foliage/unreal-viewport.png"><p>28 instances use a separate Blender foliage type. Original shared foliage assets remain available. Exact contact across every ledge and gameplay collision remain unverified.</p>'
page+='<h2>Source grass texture across the courtyard</h2><img class="world" src="GrassTerrain/Courtyard/unreal-viewport.png"><p>All 5,841 meadow transforms retained. The supplied v9 PNG is the byte-identical albedo; shallow physical relief is inferred. The new meadow components have BlockAll collision, with 26 sampled component probes passing after map reload. Two sampled lower edge tiles have obstructions in the unfiltered world query after all three cliff groups were replaced.</p><h2>Grass terrace before the cliff replacement</h2><img class="world" src="GrassTerrain/Terrace/unreal-viewport.png"><p>World XY sampling keeps the grass pattern continuous across tile transforms. Repeat scale and lighting remain visual review items. Other grass revisions retain their own pending inventory entries.</p>'
page+='<h2>Traced Blender cliff stones in the terrace</h2><img class="world" src="CliffColumn/Terrace/unreal-viewport.png"><p>Earlier terrace view: 1,333 former A/B cliff instances use the four-sided CliffColumn placement variant, with original transforms and type memberships verified after reload. Stone and grass source RGB regions are preserved in the atlas. All 26 sampled cap probes passed. This earlier capture still shows old C and moss pieces; the subsequent view below includes their replacements. Physical relief, inherited scaling, world lighting and gameplay traversal still require review.</p>'
page+='<h2>Source moss over the cliff lip</h2><img class="world" src="MossFringe/Detail/unreal-viewport.png"><p>All 209 cliff-moss instances now use the Blender MossFringe placement variant. The source color PNG is unchanged, and relief is inferred. Saved transforms and mesh/material bindings passed verification. Each placement has at least one modeled root sample inside a rebuilt cliff core or cap. Some hanging sections remain too compressed and layered under inherited scaling.</p><h2>All three cliff groups and new moss</h2><img class="world" src="MossFringe/Terrace/unreal-viewport.png"><p>Latest terrace view: all 2,076 A/B/C cliff instances use the Blender module, with all transforms verified after reload and 39 sampled cap probes passing. Other source revisions and further reference matching remain open.</p>'
page+='<h2>Moss refinement: reduced hanging depth and consistent texture size</h2><div class="views" style="grid-template-columns:repeat(2,1fr)"><figure><img src="MossFringe/WorldMapping/Before/unreal-viewport.png"><figcaption>Before: deep hanging geometry and scaled UV pattern</figcaption></figure><figure><img src="MossFringe/ThinFringe/unreal-viewport.png"><figcaption>Current: thin hanging geometry and fixed 64 cm world pattern</figcaption></figure></div><p>The hanging volume is at most 1.7 cm thick in Blender, with relief depth reduced to one quarter. All 209 placements and sampled root attachments passed after the update. The unmodified source image is projected in world space, so its size is independent of placement scaling; color and source-luminance relief no longer align one-to-one in Unreal. Three-finger repetition and the cushion edge still need closer reference matching.</p>'
page+='<h2>Source pavers modeled in Blender and placed in Unreal</h2><div class="views" style="grid-template-columns:repeat(2,1fr)"><figure><img src="TrailPatch/Before/unreal-viewport.png"><figcaption>Previous raised path</figcaption></figure><figure><img src="TrailPatch/After/unreal-viewport.png"><figcaption>Blender pavers with the original trail albedo</figcaption></figure></div><p>All 61 foliage instances and 23 static segments replaced. The canonical tile has 164 traced closed pavers; the irregular placement variant has 139 clipped pavers. Nine terrain samples per placement guide grounding. Saved transforms and bindings passed verification, as did 54 isolated imported paver/soil height probes. The same camera and 42-degree FOV were used for both world images. Straight polygon edges, differently scaled pavers and world lighting still need refinement.</p><h2>Trail connections remain under review</h2><div class="views" style="grid-template-columns:repeat(2,1fr)"><figure><img src="TrailPatch/Stairs/unreal-viewport.png"><figcaption>Staircase beneath the upper path edge</figcaption></figure><figure><img src="TrailPatch/Bridge/unreal-viewport.png"><figcaption>South bridge joint still has a gap</figcaption></figure></div><p>The staircase supports one point missed by the terrain-only query. At the south bridge joint, dense component probes still miss the centerline at offsets -355 through -340 cm. Path collision at wider-spaced approach samples does not establish continuity or underlying support. No character traversal or perfect-fidelity acceptance is claimed.</p>'
page=page.replace('South bridge joint still has a gap','South bridge joint before the timber threshold').replace('At the south bridge joint, dense component probes still miss the centerline at offsets -355 through -340 cm.','Before BridgeThreshold, dense component probes missed the centerline at offsets -355 through -340 cm. The current threshold checks and view follow below.')
page+='<h2>Blender timber threshold closes the south bridge joint</h2><div class="views" style="grid-template-columns:repeat(2,1fr)"><figure><img src="BridgeThreshold/Before/unreal-viewport.png"><figcaption>Before: open bank-to-deck joint</figcaption></figure><figure><img src="BridgeThreshold/After/unreal-viewport.png"><figcaption>Current: tapered timber threshold</figcaption></figure></div><p>A RiverCrossing placement variant with three planks, six iron fasteners, two segmented runners and a bearing crosspiece. The 14 closed parts export to 1,512 triangles and reuse the bridge atlas unchanged. All four bearing samples intersect supporting bank or bridge geometry. After map reload, 27 imported-height probes, 168 supported lane samples and 110 capsule sweeps passed. The capsule foot was held 4 cm above the measured surface; these are collision checks, not a character-controller playtest. The original reference assembly remains separate, and the full collection still has no perfect-fidelity approvals.</p>'
page+='<h2>Moss Tonic: pane, rim and leaf refinement</h2><div class="views" style="grid-template-columns:repeat(2,1fr)"><figure><img src="MossTonic/FirstPhysical/front.png"><figcaption>First physical bottle</figcaption></figure><figure><img src="MossTonic/front.png"><figcaption>Current pane grid, stepped lip and side-mounted leaf</figcaption></figure></div><img class="world" src="MossTonic/PaneRefinement/unreal-viewport.png"><p>Current mesh: 351 closed parts and 47,396 triangles, with separate glass, liquid and solid-detail materials. Three shader bindings and nine counter-support samples passed after map reload. The bright refraction strip is absent from the three inspected native views after limiting screen-space displacement; Blender and Unreal optical models are still different. Current world height is 18.392 cm at uniform scale. Exact pane/rim/leaf matching and awning lighting remain open.</p>'
page+='<h2>Trail Prism on the market counter</h2><div class="views" style="grid-template-columns:repeat(2,1fr)"><figure><img src="TrailPrism/Current/unreal-viewport.png"><figcaption>Current native three-quarter view</figcaption></figure><figure><img src="TrailPrism/Context/unreal-viewport.png"><figcaption>Placement beside the market goods</figcaption></figure></div><p>122 closed solid parts and 17,432 triangles, with separate crystal, luminous inclusion and bronze materials. The saved world passed three-slot, transform, export-hash, nine tip-contact and core-light checks. Uniform height is 21.28 cm. The world crystal is paler and flatter than the concept, and the bronze remains dark under the awning. Tier, clamp and facet matching remain open; the rear is inferred.</p>'
page+='<h2>Ember Crest on the left counter</h2><div class="views" style="grid-template-columns:repeat(2,1fr)"><figure><img src="EmberCrest/Current/unreal-viewport.png"><figcaption>Native front view of physical flame relief</figcaption></figure><figure><img src="EmberCrest/Current/Context/unreal-viewport.png"><figcaption>Shifted mounting clears the folded cloth</figcaption></figure></div><p>582 closed parts, 65,624 triangles, three packed maps and separate bronze, enamel and charcoal materials. Final saved placement, shader parameters, export hash and nine wall-contact samples passed after reload. Height is 28.628 cm. The flame pattern and rim still need refinement, and the existing awning shade is substantially darker than the concept. The rear is inferred; no perfect-fidelity acceptance is claimed.</p>'
page+='<h2>Deep Delver Mark on the right counter</h2><div class="views" style="grid-template-columns:repeat(2,1fr)"><figure><img src="DeepDelverMark/World/unreal-viewport.png"><figcaption>Native front view of the physical cavern relief</figcaption></figure><figure><img src="DeepDelverMark/Side/unreal-viewport.png"><figcaption>Oblique view of the solid frame and raised crystal</figcaption></figure></div><p>585 closed parts, 64,948 triangles, three packed textures and distinct gold, stone and crystal shaders. The saved placement, shader parameters, export hash and nine wall-contact samples passed after reload. Height is 30.036 cm. Stone joints, shorter ledges, gold socket braces and lower flanges were refined. Cavern density, depth and gold finish still need closer matching. <a href="DeepDelverMark/comparison.html">Source and revision comparison</a>. The rear and hidden supports are inferred. Fidelity remains open.</p>'
page+='<h2>Saved world lighting refinement</h2><p><a href="Lighting/comparison.html">Four paired before-and-after native views</a> compare the original cool sky fill at 2.2 with the current neutral fill at 7. Sun intensity, direction and exposure are unchanged. The shaded details are clearer, but muted metal, overly opaque tonic glass and pale prism remain unresolved. Earlier world captures above retain their original lighting.</p>'
packaging_path=out/'project-packaging-verification.json'
if packaging_path.exists():
    packaging=json.loads(packaging_path.read_text())
    page+=f'<h2>Editable project packaging</h2><p>{packaging["assets_verified"]} saved Blender projects have been opened directly in independent processes, with their own active scene and camera, authored parts, packed texture dependencies, material slots and exported geometry counts verified. This establishes source-file usability, not concept fidelity.</p>'
color_review=out/'ColorManagement/verification.json'
if color_review.exists():
    replacements={
        'MossTonic/PaneRefinement':'MossTonic/AfterContext',
        'TrailPrism/Current':'TrailPrism/After',
        'TrailPrism/Context':'TrailPrism/AfterContext',
        'EmberCrest/Current/Context':'EmberCrest/AfterContext',
        'EmberCrest/Current':'EmberCrest/After',
        'DeepDelverMark/World':'DeepDelverMark/After',
        'DeepDelverMark/Side':'DeepDelverMark/AfterSide'}
    for old,new in replacements.items():page=page.replace('src="'+old+'/unreal-viewport.png"','src="ColorManagement/'+new+'/unreal-viewport.png"')
    page+='<h2>Verified atlas color correction</h2><p>The four item views above now use corrected PNG8 atlas imports. Their prior PNG16 imports sampled encoded RGB despite the sRGB flag. Geometry and material factors are preserved; shaded appearance and concept fidelity remain open. <a href="ColorManagement/comparison.html">Original concepts and matching before/after cameras</a>.</p>'
(out/'catalog.html').write_text(page,encoding='utf-8')
print(f'Wrote {len(cards)} asset comparisons and checked their GLB exports.')

