"""Build a local evidence-backed review. Concepts are explicitly separate."""
import json,html,shutil
from pathlib import Path
R=Path(__file__).resolve().parents[3];D=R/'Docs/WorldExpansion/V6'
views=json.loads((R/'Docs/WorldExpansion/views.json').read_text())
validation=json.loads((D/'validation.json').read_text());persistence=json.loads((D/'reopened.json').read_text());traversal=json.loads((D/'traversal-receipt.json').read_text());layout=json.loads((D/'layout.json').read_text())
assert validation['passed'] and persistence['passed'] and traversal['all_routes_passed'],'Review cannot mark incomplete checks as passed'
for v in views:assert (D/'Captures'/f"{v['name']}.png").exists(),v['name']
labels={'RegionOverview':'The valley','AlderwatchCity':'Alderhaven • market city','StonegateTown':'Stonegate • fortified town','BrookmereVillage':'Brookmere • orchards','ReedbankVillage':'Reedbank • traders','HighfieldVillage':'Highfield • farmland','MountainPass':'The mountain pass','HomeInValley':'The preserved starting home','CityStreet':'Alderhaven • street level','RiverMill':'The riverside mill','OldAqueduct':'The old aqueduct','CivicCourt':'The civic terrace'}
copy={'RegionOverview':'Continuous angular terrain replaces the uniform staircase grid. The five rebuilt settlements remain connected by the inherited regional roads.', 'AlderwatchCity':'Crooked market lanes, bounded gardens, an orchard fringe and a raised civic precinct replace the repeated housing grid.', 'StonegateTown':'A bent gate street, asymmetric enclosure and masonry bastions give the upland town its own plan.', 'BrookmereVillage':'A village green, crescent lane and enclosed orchards establish a farming community.', 'ReedbankVillage':'A narrow trading street and small yards lead toward the river mill along the new mill track.', 'HighfieldVillage':'A compact settlement crescent sits beside three bounded crop fields.', 'MountainPass':'The coarse uniform shelves are replaced by continuous fractured surfaces and a quieter limestone palette.', 'HomeInValley':'Original home mesh signatures and the two source map files passed preservation checks.', 'CityStreet':'Actual imagegen limestone paving, human-scale architecture and a visible civic landmark.', 'RiverMill':'A masonry mill precinct with a modeled wheel, timber landing and traversable stairs. The wheel is static scenery; there is no milling simulation.', 'OldAqueduct':'Open masonry arches form an upland landmark reached by a new trail. This is environmental scenery.', 'CivicCourt':'A solid accessible ramp reaches the planted civic terrace and the 18m bell tower.'}
items=[dict(name=v['name'],label=labels[v['name']],copy=copy[v['name']],before=(D.parent/'V5/Captures'/f"{v['name']}.png").exists()) for v in views]
checks={'native_validation':validation['passed'],'all_routes':traversal['all_routes_passed'],'reopen':persistence['passed'],'protected_home':persistence['original_instances_preserved'],'protected_maps':persistence['protected_maps_unchanged'],'views':len(views),'route_count':len(traversal['routes'])}
(D/'review-build.json').write_text(json.dumps(checks,indent=2))
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Terrarium — Valley V6</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#101915;color:#e8ebdf}*{box-sizing:border-box}body{margin:0}header,main,footer{max-width:1480px;margin:auto;padding:28px 32px}header{display:flex;align-items:end;justify-content:space-between;gap:24px;border-bottom:1px solid #334439}small,.eyebrow{color:#b6c49e;letter-spacing:.15em;text-transform:uppercase;font-size:11px}h1{font-family:Georgia,serif;font-weight:400;font-size:48px;margin:8px 0}p{line-height:1.6;color:#becabb;max-width:940px}button{font:inherit;border:1px solid #485a4b;border-radius:7px;background:#1b2a20;color:#dce6d4;padding:10px 15px;cursor:pointer}button:hover,button[aria-pressed=true]{background:#d9e2bc;color:#182317}button:disabled{opacity:.3;cursor:default}.metrics{display:flex;flex-wrap:wrap;gap:24px;margin:0 0 25px}.metrics b{display:block;color:#e7eddb;font-size:23px}.metrics span{font-size:12px;color:#aaba9e}.layout{display:grid;grid-template-columns:230px 1fr;gap:24px}nav{display:flex;flex-direction:column;gap:7px}nav button{text-align:left;font-size:13px}.bar{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:12px}h2{font:28px Georgia,serif;margin:0}figure{margin:0;background:#07100a;border:1px solid #3b4b3d;border-radius:8px;overflow:hidden}figure img{width:100%;display:block;aspect-ratio:1.676;object-fit:contain}figcaption{padding:12px 16px;color:#b8c7ad;font-size:12px}.caption{min-height:54px}details{border-top:1px solid #354437;margin-top:28px;padding-top:20px}summary{cursor:pointer;color:#d8e4c9}details img{max-width:100%;margin-top:20px}a{color:#d4e7b0}footer{font-size:12px;color:#9dab94}ul{line-height:1.8;color:#bdc9b7}@media(max-width:800px){header{display:block}h1{font-size:36px}.layout{display:block}nav{flex-direction:row;overflow:auto;margin-bottom:20px}nav button{min-width:165px}.bar{align-items:start;flex-direction:column}header,main,footer{padding:20px}}
</style><header><div><div class="eyebrow">Terrarium / World study 06</div><h1>A valley with distinct places.</h1><p>A substantial rebuild of settlement plans, landscape surfaces and destinations. These are native Unreal captures of the saved world.</p></div><small>Unreal Engine 5.8.2</small></header><main><div class="metrics"><div><b>5</b><span>Rebuilt settlements</span></div><div><b>267</b><span>Settlement buildings</span></div><div><b>4,001</b><span>New settlement details</span></div><div><b>13 / 13</b><span>CharacterMovement routes</span></div><div><b>Verified</b><span>Save / reopen / home preservation</span></div></div><div class="layout"><nav id="nav" aria-label="Viewpoints"></nav><section><div class="bar"><h2 id="title"></h2><div><button id="before">Previous V5</button> <button id="current">Current V6</button></div></div><figure><img id="view" alt=""><figcaption id="source"></figcaption></figure><p class="caption" id="caption"></p><a id="full" target="_blank">Open full native capture ↗</a></section></div><details><summary>Imagegen art direction — concept, not a game screenshot</summary><p>The generated concept guided the layout and landmark decisions. The separate limestone texture is imported into Unreal and used by the lane and masonry materials. The implemented world does not claim to match the concept's architectural variety or density.</p><img src="../../../SourceAssets/WorldExpansion/V6/ValleyDirection.png" alt="Generated valley art direction"><a href="../../../SourceAssets/WorldExpansion/V6/ImagegenPrompts.md">Saved prompts and asset provenance</a></details><details open><summary>What was verified, and current limits</summary><ul><li>Native actor transforms, retired actor collision/visibility, 64 terrain chunks, new foliage counts, ground probes and source texture hash passed.</li><li>Thirteen possessed-character routes passed using real CharacterMovement, gravity and collision, including original regional connections, civic ramp, both stair directions and the two landmark trails.</li><li>All saved mesh instance signatures, component assignments and camera activation settings survived map reload. Original home instances and both original map files remain unchanged.</li><li>New terrain and landmark geometry has one visible LOD. Spatial streaming, full-world navigation, physical held-key control, NPC life, quests and a simulated economy are not implemented or validated by this pass.</li><li>The region still reuses a small architecture family; this is a world-building overhaul, not a finished city asset library.</li></ul><p><a href="validation.json">Native validation</a> · <a href="traversal-receipt.json">Traversal receipt</a> · <a href="reopened.json">Persistence receipt</a> · <a href="Review.md">Change notes</a></p></details></main><footer>Original V5 world retained as ValleyRegionV5Archive. No commit or push performed. Captures are native renderer output, not generated scene images.</footer><script>
const items=ITEMS;let selected=items.findIndex(x=>x.name==='AlderwatchCity'),previous=false;const nav=document.querySelector('#nav');items.forEach((v,i)=>{const b=document.createElement('button');b.textContent=v.label;b.onclick=()=>{selected=i;previous=false;render()};nav.append(b)});function render(){const v=items[selected];nav.childNodes.forEach((b,i)=>b.setAttribute('aria-pressed',i===selected));document.querySelector('#title').textContent=v.label;document.querySelector('#before').disabled=!v.before;document.querySelector('#before').setAttribute('aria-pressed',previous);document.querySelector('#current').setAttribute('aria-pressed',!previous);const src=(previous?'../V5/Captures/':'Captures/')+v.name+'.png';document.querySelector('#view').src=src;document.querySelector('#view').alt=v.label+' — native Unreal '+(previous?'V5':'V6')+' capture';document.querySelector('#full').href=src;document.querySelector('#source').textContent='Native Unreal capture • '+(previous?'Previous V5':'Current V6')+' • '+v.name;document.querySelector('#caption').textContent=v.copy}document.querySelector('#before').onclick=()=>{previous=true;render()};document.querySelector('#current').onclick=()=>{previous=false;render()};render();
</script></html>'''.replace('ITEMS',json.dumps(items))
art=D/'ArtDirection';art.mkdir(exist_ok=True)
for name in ['ValleyDirection.png','ImagegenPrompts.md']:shutil.copy2(R/'SourceAssets/WorldExpansion/V6'/name,art/name)
page=page.replace('../../../SourceAssets/WorldExpansion/V6/','ArtDirection/')
(D/'review.html').write_text(page,encoding='utf-8');(D.parent/'review.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=V6/review.html"><a href="V6/review.html">Open current V6 review</a>')
print(json.dumps(checks))
